import { ValidationError } from '../../commonTypes'

export type profileHistoryItem = {
  size: number
  list: list[]
}
export type list = {
  id: number
  firstName: string
  lastName: string
  middleName: string
  fullName: string
  currentLocation: string
  baseLocation: string
  gender: string
  bloodgroup: string
  officialBirthday: string
  realBirthday: string
  maritalStatus: string
  departmentName: string
  empManager: string
  employmentTypeName: string
  jobTypeName: string
  skypeId: string
  aboutMe: string
  phone: number
  alternativeMobile: number
  homeNumber: number
  workNumber: number
  emergencyContactName: number
  emergencyPhone: number
  emergencyRelationShip: string
  presentAddress: string
  presentCity: string
  presentZip: string
  presentLandMark: string
  permanentAddress: string
  permanentCity: string
  permanentZip: string
  permanentLandMark: string
  passportNumber: number
  passportExpDate: string
  passportIssuedPlace: string
  passportIssuedDate: string
  personName: string
  relationShip: string
  contactNumber: string
  dateOfBirth: string
  marriageDate: string
  homeCode: string
  workCode: string
  timeSlot: string
  role: string
  empRole: string
  designation: string
  releavingDate: string
  underNoticeDate: string
  underNotice: string
  manager: string
  statusName: string
  hrAssociate: string
  modifiedDate: string
  modifiedBy: string
  persistType: string
  columnName: string
  additionalInfo: string
  oldrole: string
  oldstatusName: string
  oldmanager: string
  olddesignation: string
  oldreleavingDate: string
  oldunderNoticeDate: string
  oldunderNotice: string
  oldempRole: string
  oldFirstName: string
  oldtimeSlot: string
  oldLastName: string
  oldMiddleName: string
  oldFullName: string
  oldCurrentLocation: string
  oldBaseLocation: string
  oldgender: string
  oldbloodGroup: string
  oldOfficalBirthday: string
  oldRealBirthday: string
  oldMartialStatus: string
  oldDepartmentName: string
  oldEmpManager: string
  oldEmploymentTypeName: string
  oldJobTypeName: string
  oldSkypeId: string
  oldAboutMe: string
  oldPhone: number
  oldAlternativeMobile: number
  oldHomeNumber: number
  oldWorkNumber: number
  oldEmergencyContactName: string
  oldEmergencyPhone: number
  oldEmergencyRelationShip: string
  oldPresentAddress: string
  oldPresentCity: string
  oldPresentZip: string
  oldPresentLandMark: string
  oldPermanentAddress: string
  oldPermanentCity: string
  oldPermanentZip: string
  oldPermanentLandMark: string
  oldPassportNumber: number
  oldPassportExpDate: string
  oldPassportIssuedPlace: string
  oldPassportIssuedDate: string
  oldPersonName: string
  oldRelationShip: string
  oldContactNumber: string
  oldDateOfBirth: string
  oldMarriageDate: string
  oldHomeCode: string
  oldWorkCode: string
  oldHrAssociate: string
  isAbsconeded: string
  oldisAbsconed: string
  oldComments: string
  comments: string
}
export type profileHistoryState = {
  profileHistoryList: profileHistoryItem[]
  error: ValidationError
  isLoading: boolean
}
