image: node:11.6.0

stages:
  - build
  - lint
  - test
  - sonarqube
  - deployqa

cache:
  paths:
    - node_modules/

.only-merge_requests: &only-merge_requests
  only:
    - merge_requests

Build:
  <<: *only-merge_requests
  stage: build
  allow_failure: false
  before_script:
    - echo "Executing build step"
  script:
    - echo "Installing npm package"
    - npm ci

Eslint:
  <<: *only-merge_requests
  stage: lint
  allow_failure: false
  before_script:
    - echo "Executing lint step"
  script:
    - npm run lint

Test:
  <<: *only-merge_requests
  stage: test
  allow_failure: false
  before_script:
    - echo "Executing test step"
  script:
    - npm run test:cov

Sonarqube:
  <<: *only-merge_requests
  stage: sonarqube
  allow_failure: false
  script:
    - dir
    - echo "Starting sonar analysis"
    - cmd.exe /C "sonar-scanner -X -Dsonar.projectKey=ovh-typescript-react-migration -Dsonar.projectName=OVHTypeScriptReactMigration -Dsonar.sources=src -Dsonar.qualitygate.wait=true -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info"

deploy qa:
  <<: *only-merge_requests
  stage: deployqa
  script:
    - echo "Creating a war file"
    - mvn package
    - echo "Deploying to qa environment"
    - cmd.exe /C "echo n | psftp $QA_DEPLOY_USER@$QA_DEPLOY_HOST -pw $QA_DEPLOY_PASSWORD -P 22 -b deployScripts/deploy_qa.txt"
