image: node:16

stages:
  - test
  - deployqa

Test:
  stage: test
  cache:
    key: ovh-react-typescript-migration
    paths:
      - node_modules/
  only:
    - merge_request
    - develop
    - qa
    - master
  allow_failure: false
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  before_script:
    - echo "Installing npm package"
    - npm ci
  script:
    - echo "Starting Lint"
    - npm run lint
    - echo "Starting Test"
    - npm run test:cov
    # - echo "Starting sonar analysis"
    # - dir
    # - sonar-scanner -D"sonar.projectKey=ovh-typescript-react-migration" -D"sonar.projectName=OVHTypeScriptReactMigration" -D"sonar.sources=src" -D"sonar.qualitygate.wait=true" -D"sonar.typescript.lcov.reportPaths=coverage/lcov.info"
  artifacts:
    when: always
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage

Deployqa:
  stage: deployqa
  only:
    - qa
  script:
    - echo "Creating a war file"
    - mvn package
    - echo "Deploying to qa environment"
    - cmd.exe /C "echo n | psftp $QA_DEPLOY_USER@$QA_DEPLOY_HOST -pw $QA_DEPLOY_PASSWORD -P 22 -b deployScripts/deploy_qa.txt"
