image: node:16

stages:
  - test
  - sonarqube
  - deployqa

Test:
  stage: test
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  deploy:
    only:
      - develop
  allow_failure: false
  cache:
    key: ovh-react-typescript-migration
    paths:
      - node_modules/
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - npm install
    - npm run lint
    - npm run test:cov
  artifacts:
    when: always
    reports:
      cobertura: coverage/cobertura-coverage.xml
    paths:
      - coverage

Sonarqube:
  stage: sonarqube
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "qa" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
  allow_failure: false
  script:
    - dir
    - echo "Starting sonar analysis"
    - cmd.exe /C "sonar-scanner -X -Dsonar.projectKey=ovh-typescript-react-migration -Dsonar.projectName=OVHTypeScriptReactMigration -Dsonar.sources=src -Dsonar.qualitygate.wait=true -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info"

Deployqa:
  stage: deployqa
  only:
    - qa
  script:
    - echo "Creating a war file"
    - mvn package
    - echo "Deploying to qa environment"
    - cmd.exe /C "echo n | psftp $QA_DEPLOY_USER@$QA_DEPLOY_HOST -pw $QA_DEPLOY_PASSWORD -P 22 -b deployScripts/deploy_qa.txt"
