import { LoadingState } from '../../../../commonTypes'

export type ProjectNotesTimeLine = {
  id: string
  postedBy: {
    id: number
    firstName: string
    lastName: string
    middleName: string
    designation: string
    role: string
    manager: {
      id: number
      firstName: string
      lastName: string
      middleName: null
      designation: null
      role: null
      manager: null
      designationKrasDTO: null
      employeeSubmitted: null
      managerSubmitted: null
      acknowledged: null
      fullName: string
      profilePicPath: string
      thumbPicture: string
      profilePicGeneratedPath: null
      gender: null
      dob: null
      departmentName: null
      employmentTypeName: null
      jobTypeName: null
      imageData: null
      curentLocation: null
      baseLocation: null
      officialBirthday: null
      realBirthday: null
      maritalStatus: null
      emergencyContactName: null
      emergencyPhone: null
      emergencyRelationShip: null
      grade: null
      aboutMe: null
      homeNumber: null
      workNumber: null
      presentAddress: null
      presentCity: null
      presentZip: null
      presentLandMark: null
      permanentAddress: null
      permanentCity: null
      permanentZip: null
      permanentLandMark: null
      mobile: null
      homeCode: null
      workCode: null
      skillList: null
      userName: null
      alternativeMobile: null
      dateOfJoining: null
      informationList: null
      anniversary: null
      bankInformationList: null
      bioAttendanceDtoSet: null
      dates: null
      absentCount: number
      statusName: null
      emergencyContact: null
      relievingDate: null
      observationDTOList: null
      skypeId: null
      percent: null
      passportNumber: null
      passportExpDate: null
      passportIssuedPlace: null
      passportIssuedDate: null
      token: null
      underNoticeDate: null
      candidateId: null
      underNotice: null
      emailId: null
      empManager: null
      bloodgroup: null
      rbtCvPath: null
      rbtCvName: null
      timeSlotDTO: null
      technology: null
      hrAssociate: null
      lateComingCount: null
      passportFrontPagePath: null
      passportBackPagePath: null
      passportFrontPage: null
      passportBackPage: null
      projectManager: null
      casualLeaveCount: number
      lopLeaveCount: number
      holidaysCount: number
      contractExists: null
      contractStartDate: null
      contractEndDate: null
      personalEmail: null
      experience: null
      companyExperience: null
      updatedExperience: null
      country: null
      workStatus: null
      comments: null
      vendorId: null
      vendorName: null
      countryCodeWork: null
      countryCodeMobile: null
      countryCodeHome: null
      countryCodeEmergency: null
      countryCodeAlternative: null
      address: null
    }
    designationKrasDTO: {
      id: number
      designationCode: string
      designationName: string
      comments: null
      krasWithWeitage: null
    }
    employeeSubmitted: null
    managerSubmitted: null
    acknowledged: null
    fullName: string
    profilePicPath: string
    thumbPicture: string
    profilePicGeneratedPath: null
    gender: string
    dob: null
    departmentName: string
    employmentTypeName: string
    jobTypeName: string
    imageData: null
    curentLocation: string
    baseLocation: string
    officialBirthday: string
    realBirthday: string
    maritalStatus: string
    emergencyContactName: null
    emergencyPhone: null
    emergencyRelationShip: string
    grade: null
    aboutMe: string
    homeNumber: null
    workNumber: null
    presentAddress: null
    presentCity: null
    presentZip: null
    presentLandMark: null
    permanentAddress: null
    permanentCity: null
    permanentZip: null
    permanentLandMark: null
    mobile: null
    homeCode: null
    workCode: null
    skillList: null
    userName: string
    alternativeMobile: null
    dateOfJoining: string
    informationList: null
    anniversary: null
    bankInformationList: null
    bioAttendanceDtoSet: null
    dates: null
    absentCount: 0
    statusName: string
    emergencyContact: null
    relievingDate: null
    observationDTOList: null
    skypeId: string
    percent: null
    passportNumber: null
    passportExpDate: null
    passportIssuedPlace: null
    passportIssuedDate: null
    token: null
    underNoticeDate: null
    candidateId: null
    underNotice: null
    emailId: string
    empManager: string
    bloodgroup: string
    rbtCvPath: null
    rbtCvName: null
    timeSlotDTO: {
      id: number
      name: string
      startTimeHour: string
      startTimeMinutes: string
      endTimeHour: string
      endTimeMinutes: string
      graceTime: string
    }
    technology: string
    hrAssociate: null
    lateComingCount: null
    passportFrontPagePath: null
    passportBackPagePath: null
    passportFrontPage: null
    passportBackPage: null
    projectManager: null
    casualLeaveCount: number
    lopLeaveCount: number
    holidaysCount: number
    contractExists: false
    contractStartDate: null
    contractEndDate: null
    personalEmail: string
    experience: number
    companyExperience: number
    updatedExperience: number
    country: string
    workStatus: string
    comments: null
    vendorId: null
    vendorName: null
    countryCodeWork: null
    countryCodeMobile: null
    countryCodeHome: null
    countryCodeEmergency: null
    countryCodeAlternative: null
    address: null
  }
  post: string
  postDate: string
  postImageData: null
  feedPostCommentsList: []
  project: {
    id: number
    projectName: string
    managerId: number
    startdate: string
    enddate: string
    description: string
    status: string
    managerName: string
    count: null
    billable: false
    isAllocated: null
    employeeId: null
    health: null
    client: string
    type: string
    clientId: null
    projectStartdate: null
    projectEndDate: null
    requiredResources: null
    newClient: null
    requestedBy: null
    statuEditFlag: null
    technology: null
    address: null
    personName: null
    email: null
    country: null
    organization: null
    intrnalOrNot: false
    hiveProjectName: string
    cc: null
    bcc: null
    deliveryManager: null
    projectRequestId: null
    model: string
    checkListExist: null
    projectCode: null
    projectContactPerson: string
    projectContactEmail: string
    billingContactPerson: string
    billingContactPersonEmail: string
    projectRequestMilestoneDTO: null
    platform: string
    domain: string
    clientName: string
    hiveProjectFlag: false
    allocation: null
  }
  milestone: null
  invoiceId: null
}

export type ProjectNotesState = {
  projectNotesTimeLine: ProjectNotesTimeLine[]
  isLoading: LoadingState
}
